# example compose file with a mysql db container and a db loader container
# note: spring properties passed as env variables are uppercased and underscored
version: '3'
#
services:
  db:
    image: mysql:5.5
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=testdb_root
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=testdb
      - MYSQL_DATABASE=dbtest
    networks:
      - net-spring-db
  dbsetup:
    environment:
      - MAVEN_LOCAL_REPO=/.m2/repository 
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=testdb
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/dbtest
# specify your migrations here - note the fake gav url prefix
# migations are performed in the order they appear below
      - DB_MIGRATIONS=
        [
            {   "changeLogRoot":"gav:au.com.cybernostics.changesets:changeset1",
                "changelogs":[
                    "db/changelog/db.changelog-master.yaml",
                    "db/changelog2/db.changelog-master.yaml"
                    ]
            }
        ]
    image: aucybernostics/db-data-load:0.0.1-SNAPSHOT
    networks:
      - net-spring-db
    volumes:
      - /home/jason/.m2:/.m2    
    depends_on: 
      - db  
networks:
  net-spring-db:
    driver: bridge    
